version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-server
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD: batatinha123'
      POSTGRES_DB: sunfire_bank
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: